"""SR-D-206 initial schema

Revision ID: b4dd5669ca62
Revises: 
Create Date: 2026-09-10 15:44:55.039352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4dd5669ca62'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('link', sa.String(length=1000), nullable=False),
    sa.Column('link_hash', sa.String(length=64), nullable=False),
    sa.Column('keyword', sa.String(length=64), nullable=False),
    sa.Column('site', sa.String(length=64), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('user_id', sa.String(length=26), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_articles')),
    sa.UniqueConstraint('link_hash', name='uq_articles_link_hash'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('executions',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('collected_count', sa.Integer(), nullable=False),
    sa.Column('new_count', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('node_logs', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.String(length=26), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_executions')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('feed_sources',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('url_template', sa.String(length=1000), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('user_id', sa.String(length=26), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feed_sources')),
    sa.UniqueConstraint('name', name='uq_feed_sources_name'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('keywords',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('value', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=26), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_keywords')),
    sa.UniqueConstraint('user_id', 'value', name='uq_keywords_user_id_value'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('settings',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('mail_subject', sa.String(length=200), nullable=False),
    sa.Column('mail_to', sa.String(length=255), nullable=False),
    sa.Column('max_per_source', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=26), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settings')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    op.drop_table('keywords')
    op.drop_table('feed_sources')
    op.drop_table('executions')
    op.drop_table('articles')
    # ### end Alembic commands ###
