"""SR-F-805 schedule time in settings and execution trigger

Revision ID: f18e4ef091e4
Revises: b4dd5669ca62
Create Date: 2026-09-11 14:35:30.783157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f18e4ef091e4'
down_revision: Union[str, Sequence[str], None] = 'b4dd5669ca62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('executions', sa.Column('trigger', sa.String(length=16), server_default=sa.text("'manual'"), nullable=False))
    op.add_column('settings', sa.Column('schedule_hour', sa.Integer(), server_default=sa.text('8'), nullable=False))
    op.add_column('settings', sa.Column('schedule_minute', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'schedule_minute')
    op.drop_column('settings', 'schedule_hour')
    op.drop_column('executions', 'trigger')
    # ### end Alembic commands ###
